import {
  GridMetrics,
  GridAsset,
  AIReliabilityPrediction,
  GridAlertItem,
  AnomalyEvent,
} from '../types/grid';

export const INITIAL_METRICS: GridMetrics = {
  voltage: 229,
  frequency: 49.98,
  current: 82,
  powerFactor: 0.96,
  systemLoadPct: 76,
  currentLoadMW: 15.2,
  peakLoadMW: 18.7,
  averageLoadMW: 13.8,
  reliabilityScore: 94,
  activeAlertsCount: 3,
  faultRiskPct: 8,
  connectedAssetsCount: 128,
  renewableContributionPct: 34,
  lastUpdated: '5 seconds ago',
};

export const INITIAL_ASSETS: GridAsset[] = [
  {
    id: 'T-001',
    name: 'Transformer Unit 01',
    type: 'Transformer',
    location: 'Substation A',
    temperatureC: 61,
    loadPct: 72,
    healthPct: 94,
    status: 'Healthy',
    risk: 'Low',
    lastUpdate: '2 mins ago',
    coordinates: { x: 32, y: 35 },
    specifications: {
      voltageLevel: '132 / 33 kV',
      ratedCapacity: '40 MVA',
      coolingType: 'ONAF (Forced Air)',
      oilQualityIndex: 96,
      vibrationHarmonics: 1.2,
    },
    predictiveData: {
      failureRiskPct: 6,
      temperatureTrend: 'Stable',
      loadTrend: 'Stable',
      lastMaintenance: '2026-08-14',
      nextRecommendedInspection: '90 Days',
      contributingFactors: [
        { factor: 'Optimal oil dielectric breakdown voltage', impactPct: 4 },
        { factor: 'Balanced 3-phase loading', impactPct: 2 },
      ],
    },
  },
  {
    id: 'T-002',
    name: 'Transformer Unit 02',
    type: 'Transformer',
    location: 'Substation B',
    temperatureC: 78,
    loadPct: 91,
    healthPct: 74,
    status: 'Warning',
    risk: 'Medium',
    lastUpdate: '1 min ago',
    coordinates: { x: 68, y: 38 },
    specifications: {
      voltageLevel: '132 / 33 kV',
      ratedCapacity: '40 MVA',
      coolingType: 'ONAF (Forced Air)',
      oilQualityIndex: 78,
      vibrationHarmonics: 3.4,
    },
    predictiveData: {
      failureRiskPct: 28,
      temperatureTrend: 'Increasing',
      loadTrend: 'Increasing',
      lastMaintenance: '2026-06-20',
      nextRecommendedInspection: '6 Days',
      contributingFactors: [
        { factor: 'High loading continuous duty', impactPct: 28 },
        { factor: 'Increasing core thermal gradient', impactPct: 21 },
        { factor: 'Voltage fluctuations on downstream feeder', impactPct: 14 },
        { factor: 'Historical tap-changer arcing patterns', impactPct: 9 },
      ],
    },
  },
  {
    id: 'T-003',
    name: 'Transformer Unit 03',
    type: 'Transformer',
    location: 'Substation C',
    temperatureC: 64,
    loadPct: 68,
    healthPct: 92,
    status: 'Healthy',
    risk: 'Low',
    lastUpdate: '3 mins ago',
    coordinates: { x: 48, y: 70 },
    specifications: {
      voltageLevel: '66 / 11 kV',
      ratedCapacity: '25 MVA',
      coolingType: 'ONAN (Natural)',
      oilQualityIndex: 94,
      vibrationHarmonics: 1.1,
    },
    predictiveData: {
      failureRiskPct: 7,
      temperatureTrend: 'Stable',
      loadTrend: 'Stable',
      lastMaintenance: '2026-07-05',
      nextRecommendedInspection: '60 Days',
      contributingFactors: [
        { factor: 'Moderate baseload demand', impactPct: 4 },
        { factor: 'Good thermal dissipation', impactPct: 3 },
      ],
    },
  },
  {
    id: 'T-004',
    name: 'Transformer Unit 04',
    type: 'Transformer',
    location: 'Industrial Feeder Hub',
    temperatureC: 75,
    loadPct: 88,
    healthPct: 81,
    status: 'Warning',
    risk: 'Medium',
    lastUpdate: '4 mins ago',
    coordinates: { x: 22, y: 55 },
    specifications: {
      voltageLevel: '33 / 11 kV',
      ratedCapacity: '30 MVA',
      coolingType: 'ONAF',
      oilQualityIndex: 82,
      vibrationHarmonics: 2.8,
    },
    predictiveData: {
      failureRiskPct: 22,
      temperatureTrend: 'Increasing',
      loadTrend: 'Increasing',
      lastMaintenance: '2026-05-18',
      nextRecommendedInspection: '12 Days',
      contributingFactors: [
        { factor: 'Industrial arc-furnace cyclic loading', impactPct: 19 },
        { factor: 'Ambient heat accumulation', impactPct: 15 },
      ],
    },
  },
  {
    id: 'D-014',
    name: 'Distribution Node D-14',
    type: 'Distribution Node',
    location: 'Sector 3 Commercial Zone',
    temperatureC: 69,
    loadPct: 94,
    healthPct: 68,
    status: 'Critical',
    risk: 'High',
    lastUpdate: 'Just now',
    coordinates: { x: 78, y: 65 },
    specifications: {
      voltageLevel: '11 kV / 415 V',
      ratedCapacity: '10 MVA',
      coolingType: 'Air Cooled',
    },
    predictiveData: {
      failureRiskPct: 64,
      temperatureTrend: 'Increasing',
      loadTrend: 'Increasing',
      lastMaintenance: '2026-04-10',
      nextRecommendedInspection: 'Immediate (24h)',
      contributingFactors: [
        { factor: 'Sub-cycle voltage sag transients', impactPct: 32 },
        { factor: 'Phase unbalance exceeding 4%', impactPct: 24 },
        { factor: 'Peak commercial EV fast-charging surge', impactPct: 18 },
      ],
    },
  },
  {
    id: 'D-008',
    name: 'Distribution Node D-08',
    type: 'Distribution Node',
    location: 'Harbor Gate Waterfront',
    temperatureC: 58,
    loadPct: 62,
    healthPct: 95,
    status: 'Healthy',
    risk: 'Low',
    lastUpdate: '5 mins ago',
    coordinates: { x: 85, y: 25 },
    specifications: {
      voltageLevel: '11 kV / 415 V',
      ratedCapacity: '15 MVA',
      coolingType: 'Air Cooled',
    },
  },
  {
    id: 'SS-A',
    name: 'Substation A (Bulk 400kV)',
    type: 'Substation',
    location: 'North Transmission Corridor',
    temperatureC: 48,
    loadPct: 76,
    healthPct: 96,
    status: 'Healthy',
    risk: 'Low',
    lastUpdate: '1 min ago',
    coordinates: { x: 30, y: 20 },
    specifications: {
      voltageLevel: '400 / 132 kV',
      ratedCapacity: '250 MVA',
      coolingType: 'GIS Switchgear',
    },
  },
  {
    id: 'SS-B',
    name: 'Substation B (Grid Tie 132kV)',
    type: 'Substation',
    location: 'East Industrial Junction',
    temperatureC: 62,
    loadPct: 89,
    healthPct: 82,
    status: 'Warning',
    risk: 'Medium',
    lastUpdate: 'Just now',
    coordinates: { x: 70, y: 22 },
    specifications: {
      voltageLevel: '132 / 33 kV',
      ratedCapacity: '120 MVA',
      coolingType: 'Air Insulated',
    },
  },
  {
    id: 'SOLAR-01',
    name: 'Solaria Solar PV Farm',
    type: 'Solar Farm',
    location: 'Valley Green Inflow',
    temperatureC: 42,
    loadPct: 58,
    healthPct: 98,
    status: 'Healthy',
    risk: 'Low',
    lastUpdate: '2 mins ago',
    coordinates: { x: 50, y: 88 },
    specifications: {
      voltageLevel: '33 kV Inflow',
      ratedCapacity: '25 MW Peak',
      coolingType: 'Liquid Cooled Inverters',
    },
  },
  {
    id: 'BESS-01',
    name: 'Metro BESS Battery Storage 20MW',
    type: 'BESS Storage',
    location: 'Substation B Outpost',
    temperatureC: 38,
    loadPct: 72,
    healthPct: 97,
    status: 'Healthy',
    risk: 'Low',
    lastUpdate: '1 min ago',
    coordinates: { x: 60, y: 50 },
    specifications: {
      voltageLevel: '33 kV Bidirectional',
      ratedCapacity: '20 MW / 40 MWh',
      coolingType: 'HVAC Enclosures',
    },
  },
];

export const INITIAL_PREDICTIONS: AIReliabilityPrediction[] = [
  {
    id: 'pred-overall',
    category: 'Overall Grid Risk',
    probabilityPct: 8,
    trend: 'stable',
    status: 'LOW',
    shortExplanation: 'Grid conditions are stable with adequate spinning reserves and nominal voltage headroom.',
    recommendedAction: 'Maintain automated economic dispatch and continue routine PMU monitoring.',
    contributingFactors: [
      { factor: 'Nominal busbar voltage (229V)', impactPct: 3 },
      { factor: 'Stable 49.98 Hz frequency regulation', impactPct: 3 },
      { factor: 'Substation B thermal load concentration', impactPct: 2 },
    ],
  },
  {
    id: 'pred-fault',
    category: 'Fault Probability',
    probabilityPct: 8,
    trend: 'down',
    status: 'LOW',
    shortExplanation: 'Low likelihood of unscheduled breaker trip across transmission corridors.',
    recommendedAction: 'Verify differential relay settings on transmission line TL-101.',
    contributingFactors: [
      { factor: 'Zero phase-to-ground flashover indicators', impactPct: 4 },
      { factor: 'Lightning strike activity clear in region', impactPct: 2 },
      { factor: 'Minor vibration on Transformer T-002', impactPct: 2 },
    ],
  },
  {
    id: 'pred-overload',
    category: 'Overload Probability',
    probabilityPct: 12,
    trend: 'up',
    status: 'LOW',
    shortExplanation: 'Evening peak ramp projected to test 91% capacity on Substation B tie-feeder.',
    recommendedAction: 'Queue 4.5 MW BESS discharge between 18:30 and 20:30 to shave evening peak.',
    contributingFactors: [
      { factor: 'Commercial cooling load ramp', impactPct: 6 },
      { factor: 'EV fast-charging concurrency in Sector 3', impactPct: 4 },
      { factor: 'Solar irradiance diurnal fade at 18:15', impactPct: 2 },
    ],
  },
  {
    id: 'pred-voltage',
    category: 'Voltage Instability Risk',
    probabilityPct: 5,
    trend: 'stable',
    status: 'LOW',
    shortExplanation: 'System reactive power margin is strong with power factor at 0.96 lagging.',
    recommendedAction: 'Keep Capacitor Bank CB-02 in auto-standby for VAR support.',
    contributingFactors: [
      { factor: 'Distribution Node D-14 localized sags', impactPct: 3 },
      { factor: 'Heavy motor inrush at industrial zone', impactPct: 2 },
    ],
  },
  {
    id: 'pred-equipment',
    category: 'Equipment Failure Risk',
    probabilityPct: 9,
    trend: 'up',
    status: 'LOW',
    shortExplanation: 'Transformer T-04 shows increasing thermal stress. Monitor loading and inspect the asset if the trend continues.',
    recommendedAction: 'Dispatch maintenance technician to inspect T-002 cooling radiator fans within 6 days.',
    contributingFactors: [
      { factor: 'High transformer loading', impactPct: 28 },
      { factor: 'Increasing temperature', impactPct: 21 },
      { factor: 'Recent voltage fluctuations', impactPct: 14 },
      { factor: 'Historical fault pattern', impactPct: 9 },
    ],
  },
];

export const INITIAL_ALERTS: GridAlertItem[] = [
  {
    id: 'ALT-101',
    severity: 'HIGH',
    assetId: 'T-002',
    assetName: 'Transformer T-002',
    time: '12 mins ago',
    description: 'Transformer T-002 approaching high-load threshold.',
    suggestedAction: 'Engage forced cooling fan bank 2 and transfer 6 MW to Substation A tie-feeder.',
    status: 'ACTIVE',
  },
  {
    id: 'ALT-102',
    severity: 'MEDIUM',
    assetId: 'D-014',
    assetName: 'Distribution Node D-14',
    time: '28 mins ago',
    description: 'Voltage fluctuation detected at Distribution Node D-14.',
    suggestedAction: 'Command automated On-Load Tap Changer (OLTC) +1 step at feeder head.',
    status: 'ACTIVE',
  },
  {
    id: 'ALT-103',
    severity: 'LOW',
    assetId: 'SEC-03',
    assetName: 'Sector 3 Commercial Zone',
    time: '45 mins ago',
    description: 'Load increase detected in Sector 3.',
    suggestedAction: 'Monitor EV charging cluster and verify BESS storage availability for peak shaving.',
    status: 'ACTIVE',
  },
];

export const INITIAL_ANOMALIES: AnomalyEvent[] = [
  {
    id: 'anom-1',
    time: '11:02',
    status: 'Normal',
    dimension: 'System',
    whatChanged: 'Voltage and load re-stabilized within nominal IEEE 519 tolerances.',
    assetAffected: 'All Grid Assets',
    contributingFactors: ['Capacitor bank energized', 'Feeder load redistribution completed'],
  },
  {
    id: 'anom-2',
    time: '10:51',
    status: 'Anomaly',
    dimension: 'Load',
    whatChanged: 'Load anomaly detected: Sudden 4.2 MW ramp over 90 seconds.',
    assetAffected: 'Distribution Node D-14',
    contributingFactors: ['High transformer loading: +28%', 'Industrial shift start concurrency', 'EV fleet fast-charge demand'],
  },
  {
    id: 'anom-3',
    time: '10:48',
    status: 'Anomaly',
    dimension: 'Voltage',
    whatChanged: 'Voltage anomaly detected: Transient dip to 216 V (-5.6% excursion).',
    assetAffected: 'Distribution Node D-14',
    contributingFactors: ['Inrush current on feeder 4B', 'Motor soft-starter delay', 'Recent voltage fluctuations: +14%'],
  },
  {
    id: 'anom-4',
    time: '10:41',
    status: 'Normal',
    dimension: 'Frequency',
    whatChanged: 'Frequency steady at 49.99 Hz with minor spinning reserve governor adjustment.',
    assetAffected: 'Substation A (Bulk 400kV)',
    contributingFactors: ['Standard AGC balance'],
  },
  {
    id: 'anom-5',
    time: '10:32',
    status: 'Normal',
    dimension: 'System',
    whatChanged: 'Nominal baseline telemetry across all 128 connected physical assets.',
    assetAffected: 'Fleet Wide',
    contributingFactors: ['Normal morning diurnal profile'],
  },
];

export const HOURLY_LOAD_DATA = [
  { time: '00:00', current: 11.2, previous: 11.5, predicted: 11.0 },
  { time: '02:00', current: 10.4, previous: 10.8, predicted: 10.2 },
  { time: '04:00', current: 9.8, previous: 10.1, predicted: 9.6 },
  { time: '06:00', current: 12.1, previous: 11.9, predicted: 12.0 },
  { time: '08:00', current: 14.5, previous: 14.0, predicted: 14.2 },
  { time: '10:00', current: 15.2, previous: 14.8, predicted: 15.0 },
  { time: '12:00', current: 15.4, previous: 15.1, predicted: 15.3 },
  { time: '14:00', current: 15.0, previous: 14.7, predicted: 14.9 },
  { time: '16:00', current: 16.2, previous: 15.8, predicted: 16.0 },
  { time: '18:00', current: 17.8, previous: 17.4, predicted: 17.6 },
  { time: '19:00', current: null, previous: 18.2, predicted: 18.7 }, // Predicted Peak
  { time: '20:00', current: null, previous: 17.9, predicted: 18.1 },
  { time: '22:00', current: null, previous: 14.1, predicted: 14.3 },
];
